samples:
  Day7RetroDam_DamLeo1_K27ac_FACS_RA_1:                                                       # Change the name of your sample here
    fastq_path:
      /path/to/your/project/raw_fastq/                                                   # Modify path to fastq files here
    barcodes:                                                                            # Define your different antibody barcodes here
      Dam.RA0.rep1: GGCTCTGA
      Dam.RA05.rep1: TAATCTTA
      Dam.RA25.rep1: CAGGACGT
      K27ac.RA0.rep1: TATAGCCT
      K27ac.RA05.rep1: ATAGAGGC
      K27ac.RA25.rep1: CCTATCCT

general:
  tempdir: /path/to/your/project/temp/   # Modify path to a tmp folder already created here
  cellranger_software: /path/to/your/cellranger_ATAC/cellranger-atac-2.1.0/bin/cellranger-atac             # Modify the path to cellranger binaries here
  cellranger_ref: /path/to/your/cellranger_ATAC/refdata-cellranger-arc-mm10-2020-A-2.0.0/   # Modify the path to cellranger reference here
  macs_genome: mm       
