#!/bin/bash

#### Working directory.
WORKDIR="/path/to/your/project"
cd "$WORKDIR"

# Input bigwig file (3 columns: FileName_sample, FileName_ctrl, SampleName), which were generated by QuasR (e.g., QuasR_bigwig.R)
# FileName_sample is the path to Dam-POI bigwig. FileName_ctrl is the path to FreeDam bigwig.
INPUT_FILE="bigwig_files_for_bigwigCompare.txt"

# Output directory (stores the resulting BigWig files)
OUTPUT_DIR="/path/to/your/project/bigwig_FreeDamNorm/"
mkdir -p "$OUTPUT_DIR"

# Read the input file line by line
while IFS=$'\t' read -r SAMPLE_BW CTRL_BW SAMPLE_NAME; do
    # Skip the header line
    if [[ "$SAMPLE_BW" == "FileName_sample" ]]; then
        continue
    fi

    # Output BigWig file name (based on the sample name)
    OUTPUT_BW="${OUTPUT_DIR}/${SAMPLE_NAME}_FreeDamNorm_bin1k_log2.bw"

    # Skip if the output file already exists
    if [ -f "$OUTPUT_BW" ]; then
        echo "BigWig already exists for $SAMPLE_NAME. Skipping..."
        continue
    fi

    echo "Processing Sample: $SAMPLE_NAME"
    echo "  BigWig1: $SAMPLE_BW"
    echo "  BigWig2: $CTRL_BW"

    # Run bigwigCompare
    # Possible values for --operation:
    #   ratio    => Raw ratio (BigWig1 / BigWig2)
    #   log2     => log2(BigWig1 / BigWig2)
    #   subtract => Difference (BigWig1 - BigWig2)
    #   add      => Sum (BigWig1 + BigWig2)
    #   mean     => Average ((BigWig1 + BigWig2) / 2)
    #
    # --pseudocount 0 is also possible. To avoid division by zero, you can set it to 1-10 as needed.
    # --binSize 1000: Splits into bins of 1000bp for calculation. You can adjust 100-1000
    bigwigCompare \
      -b1 "$SAMPLE_BW" \
      -b2 "$CTRL_BW" \
      --operation log2 \
      --binSize 1000 \
      --pseudocount 10 \
      --outFileName "$OUTPUT_BW" \
      --outFileFormat bigwig \
      --numberOfProcessors 8

    # Check if the output file was created successfully
    if [ ! -f "$OUTPUT_BW" ]; then
        echo "Error: BigWig file was not created for $SAMPLE_NAME." >&2
    else
        echo "Successfully created: $OUTPUT_BW"
    fi

done < "$INPUT_FILE"

echo "All processing completed."
