#!/bin/bash
#### Working directory. 
WORKDIR="/path/to/your/project"
cd "$WORKDIR"

GENOMEINDEX="/path/to/your/bowtie2Indes"
GENOMEFASTA="/path/to/your/BSgenome.Mmusculus.UCSC.mm10.fa"

# /path/to/your/project/trim_damtag contains trimmed fastq files generated by trim_damtag.sh (cutadapt)
# /path/to/your/project/bam_damtag is the output directory for bam files
for fqfile1 in trim_damtag/*_R1_001.fastq.gz
do
	fqfile2=${fqfile1%_R1_001.fastq.gz}_R2_001.fastq.gz
	outfileSam="bam_damtag/$(basename ${fqfile1/_R1_001.fastq.gz/.sam})"
	outfileBam="bam_damtag/$(basename ${fqfile1/_R1_001.fastq.gz/.bam})"
	stderrfile="bam_damtag/$(basename ${fqfile1/_R1_001.fastq.gz/.stderr})"
	if [[ ! -e "${outfileBam}" ]]
	then 
		echo "aligning $fileq1..."
		bowtie2 --fr --minins 0 --maxins 1000 --no-discordant --dovetail --threads 8 -x $GENOMEINDEX -1 $fqfile1 -2 $fqfile2 -S $outfileSam 2> $stderrfile
		echo "converting to sorted and indexed bam..."
		samtools view -uT $GENOMEFASTA $outfileSam | samtools sort  -O bam -T $outfileBam -o $outfileBam
		samtools index $outfileBam
		echo "done"
	else
		echo "skipping existing $outfileBam"
	fi
done

# remove sam files

rm bam_damtag/*sam

 